In [ ]:
print("BEM VINDO A CALCULADORA DE IMC!!!")
peso= int(input("Digite o seu peso: "))
altura= float(input("Digite sua altura: "))
IMC= peso/(altura*altura) 
print("Seu IMC é: ", IMC)

In [ ]:
cidade= input("Digite o nome da sua cidade: ")
ano= int(input("Digite o ano recorrente: "))
temperatura= int(input("Digite a temperatura média da sua cidade: "))
print("O nome da sua cidade é ", cidade, ", o ano recorrente é ", ano, ", e a temperatura média da sua cidade é ", temperatura)

In [ ]:
opcao= 1
while opcao != 0:
  print("BEM VINDO A CALCULADORA!!!")
  num1= float(input("Digite o primeiro número: "))
  num2= float(input("Digite o segundo número: "))
  print("OPERAÇÕES DISPONÍVEIS:")
  print("1- Soma")
  print("2- Subtração")
  print("3- Multiplicação")
  print("4- Divisão")
  operacao= int(input("Digite o n° da operação desejada: "))
  if operacao == 1:
    resultado= num1 + num2
  elif operacao == 2:
    resultado= num1 - num2
  elif operacao == 3:
    resultado= num1 * num2
  elif operacao == 4:
    resultado= num1 / num2
  else:
    print("Número inválido, Digite novamente.")
  print("Resultado: ", resultado)
  opcao= int(input("Digite 0 para sair da calculadora ou 1 para fazer uma nova operação: "))
print("Fechando calculadora...")
print("Programa fechado!")

In [ ]:
opcao= 1
while opcao != 0:
  print("BEM VINDO A CALCULADORA MAIOR E MENOR!!!")
  num1= float(input("Digite o primeiro número: "))
  num2= float(input("Digite o segundo número: "))
  if num1 > num2:
    print("O número 1 é maior que o número 2.")
  elif num1 < num2:
    print("O número 2 é maior que o número 1.")
  else:
    print("Os números são iguais.")
  opcao= int(input("Digite 0 para sair da calculadora ou 1 para fazer uma nova operação: "))
print("Fechando calculadora...")
print("Programa fechado!")

In [ ]:
print("BEM VINDO AO DETECTOR DE PAR OU IMPAR!!!")
num= int(input("Digite um número: "))
if num % 2 == 0:
    print("O número é par.")
else:
    print("O número é impar.")

In [ ]:
print("BEM VINDO AO CARTÓRIO DO PINTA")
print("OPÇÕES DISPONÍVEIS")
print("C ()Casado")
print("S ()Solteiro")
print("D ()Divorciado")
print("V ()Viúvo")
print("O ()Outros")
civil = input("Digite seu estado civil: ").upper()
if civil == "C":
    print("C - Casado")
elif civil == "S":
    print("S - Solteiro")
elif civil == "D":
    print("D - Divorciado")
elif civil == "V":
    print("V - Viúvo")
else:
    print("O - Outros")

In [ ]:
idade = int(input("Digite a sua idade: "))
if idade > 16 and idade < 18:
    print("Seu voto é facultativo.")
elif idade >= 70:
    print("Seu voto é facultativo.")
elif idade <= 16:
    print("Não pode votar.")
else:
    print("Seu voto é obrigatório.")

In [ ]:
idade = int(input("Digite a sua idade nadador: "))
if idade >= 5 and idade <= 7:
    print("Infantil A")
elif idade >= 8 and idade <= 11:
    print("Infantil B")
elif idade >= 12 and idade <= 13:
    print("Juvenil A")
elif idade >= 14 and idade <= 17:
    print("Juvenil B")
else:
    print("Adultos")

In [ ]:
opcao= 1
while opcao != 0:
  print("BEM VINDO A CALCULADORA!!!")
  num1= float(input("Digite o primeiro número: "))
  num2= float(input("Digite o segundo número: "))
  print("OPERAÇÕES DISPONÍVEIS:")
  print("1- Soma")
  print("2- Subtração")
  print("3- Multiplicação")
  print("4- Divisão")
  operacao= int(input("Digite o n° da operação desejada: "))
  if operacao == 1:
    resultado= num1 + num2
  elif operacao == 2:
    resultado= num1 - num2
  elif operacao == 3:
    resultado= num1 * num2
  elif operacao == 4:
    resultado= num1 / num2
  else:
    print("Número inválido, Digite novamente.")
  print(f"Resultado: {resultado:.2f}")
  opcao= int(input("Digite 0 para sair da calculadora ou 1 para fazer uma nova operação: "))
print("Fechando calculadora...")
print("Programa fechado!")

In [ ]:
numero=0
soma= int(1)
while soma != 0:
    soma= int(input("Digite um número, para encerrar digite 0:"))
    numero += soma
print(f"A soma de todos os números que você digitou é: {numero}")

In [ ]:
cont = 0
resultado = 0
op = 1
while op != 0:
    nota= float(input("Digite a sua nota para obter a média: "))
    resultado += nota
    cont += 1
    op= int(input("Digite 1 para adicionar mais uma nota, ou 0 para encerrar a operação: "))
resultado_final = resultado / cont
print("A média aritmética das suas notas é: ", resultado_final)

In [ ]:
x = int(input("Digite o número que você quer visualizar a tabuada: "))
for i in range(1,11,1):
    print(f"{x} x {i} = {x*i}")

In [ ]:
for i in range (10, 0, -1):
    print(f"6 x {i} = {6 * x}")

In [ ]:
x = int(input("Digite o número que você quer visualizar a tabuada: "))
for i in range(10,0,-1):
    print(f"{x} x {i} = {x*i}")

In [ ]:
x = int(input("Digite o número que você quer visualizar o fatorial: "))
fat = 1
for i in range(1, x + 1, 1):
    fat *= i
print(f"O fatorial do número {x} é: {fat}") 

In [ ]:
primeiro_termo = int(input("Digite o primeiro termo da PA: "))
razao = int(input("Digite a razão da PA: "))
final = int(input("Digite o último termo da PA: "))

print("-" * 20)
print("Progressão Aritmética:")

for i in range(primeiro_termo, final+1, razao):
    print(i, end=" -> ")

print("FIM")
print("-" * 20)

In [ ]:
termo1 = float(input("Digite o primeiro termo da PG: "))
razao = float(input("Digite a razão da PG: "))
final = int(input("Digite quantos termos você quer mostrar: "))

print(f"\nProgressão Geométrica ({final} termos):")

for i in range(final):
    termo_atual = termo1 * (razao ** i)
    print(f"Termo {i+1}: {termo_atual}")

In [ ]:
inicio= int(input("Digite o primeiro termo: "))
final= int(input("Digite o número final: "))
razao= int(input("Digite a razão da PG: "))
print("Progressão Geométrica:")

termo=inicio
for i in range(inicio,final+1):
    if termo<=final:
        print(termo,end=",")
        termo*=razao
    else:
        break

In [ ]:
inicio = int(input("Digite o primeiro termo: "))
final = int(input("Digite o número final: "))
razao = int(input("Digite a razão da PG: "))
print("Progressão Geométrica:")

termo = inicio
for i in range(inicio, final + 1):
    if termo <= final:
        proximo = termo * razao
        
        if proximo > final:
            print(termo, end=".")
        else:
            print(termo, end=",")
            
        termo = proximo
    else:
        break

In [ ]:
n = int(input("Digite o número de elementos que você quer visualizar a SF: "))
a, b = 0, 1

print("-" * 30)
print("Sequência de Fibonacci:")

for _ in range(n):
    print(a, end=" -> ")
    a, b = b, a + b

print("FIM")
print("-" * 30)

In [ ]:
n = int(input("Digite o número de elementos que você quer visualizar a SF: "))
anterior = 0
atual = 1
print("Sequência Fibonacci: ")
for i in range(n):
    print(atual,end=" ")
    proximo=anterior+atual
    anterior=atual
    atual=proximo

In [ ]:
letra = ["a", "b", "c", "d", "e", "f"]
print(f"Tamanho da lista: {len(letra)}")
print(f"Índice da letra b: {letra.index("b")}")
var = input("Informe o valor procurado: ")
if var.lower() in letra:
    print(f"A letra {var.lower()}, está na lista.")
else:
    print (f"A letra {var.lower()}, não está na lista")

In [ ]:
nova=[]
num=int(input("Digite um número para a lista (0 para sair): "))
while num != 0:
    nova.append(num)
    num=int(input("Digite um número para a lista (0 para sair): "))
print(nova)

In [ ]:
lista = [5, 4, 3, 2, 1]
print(lista)

In [ ]:
lista = [1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9, 10.0]
lista.reverse()
print(lista)

In [ ]:
notas = []
cont = 1
while cont != 5:
    inserir = float(input(f"Digite a nota {cont}: "))
    notas.append (inserir)
    cont+=1
print(notas)
soma=0
for i in notas:
    soma += i #OU sum(notas) para somar todos os termos da lista
media = soma / (cont-1) #OU media = soma / len(notas)
print(f"A média das notas é: {media:.2f}")

In [2]:
tupla = 1,2,3,4
print(tupla[1])
#unica diferença de tupla para lista é que a lista é mútavel e a tupla não, ou seja, não da para alterar/mexer

2


In [3]:
dic = {"Curso":"Python", "Professor":"Ricardo"}
print(f"O curso de {dic["Curso"]}, é ministrado pelo professor {dic["Professor"]}")

O curso de Python, é ministrado pelo professor Ricardo


In [4]:
produtos = {
    "Mouse":98.75,
    "Teclado":125.65,
    "Monitor":134.78,
    "Gabinete":170.00,
    "HD Externo":510.50,
    "Headset":125.45}
while True:
  produto= input("Informe o produto a pesquisar o preço ou fim para sair: ")
  if produto == "fim":
    break
  if produto in produtos:
    print(f"Produto {produto} custa {produtos[produto]}$.")
  else:
    print(f"Produto {produto} não encontrado.")

Produto Mouse custa 98.75$.


In [5]:
dic = {"Nome":"Fulano", "Sobrenome":"De tal"}
local = {"UF":"SP", "Cidade":"São Carlos"}
dic2 = dic.copy()
dic.update(local)
print(len(dic))
print(f"dic: {dic}")
print(f"dic2: {dic2}")

4
dic: {'Nome': 'Fulano', 'Sobrenome': 'De tal', 'UF': 'SP', 'Cidade': 'São Carlos'}
dic2: {'Nome': 'Fulano', 'Sobrenome': 'De tal'}


In [6]:
livro1 = {
  "Título":"O grande campeão",
  "Autor":"Pinta",
  "Ano":2026  
}

livro2 = {
  "Título":"O mar serenou",
  "Autor":"Maria Helena",
  "Ano":2024  
}

livro3 = {
  "Título":"A praia",
  "Autor":"Deus",
  "Ano":2000  
}

for chave, valor in livro1.items():
  print(f"{chave}: {valor}", end=" | ")

for chave, valor in livro2.items():
  print(f"{chave}: {valor}", end=" | ")  
  
for chave, valor in livro3.items():
  print(f"{chave}: {valor}", end=" | ")

Título: O grande campeão | Autor: Pinta | Ano: 2026 | Título: O mar serenou | Autor: Maria Helena | Ano: 2024 | Título: A praia | Autor: Deus | Ano: 2000 | 

In [7]:
livros = [
  {
    "Título":"O grande campeão",
    "Autor":"Pinta",
    "Ano":2026   
  },  

  {
    "Título":"O mar serenou",
    "Autor":"Maria Helena",
    "Ano":2024   
  },

  {
    "Título":"A praia",
    "Autor":"Deus",
    "Ano":2000   
  }             
]

print("Informações dos livros: ")
cont=1
for livro in livros:
  print(f"Título{cont}: {livro["Título"]}, Autor{cont}: {livro["Autor"]}, Ano{cont}: {livro["Ano"]}")
  cont+=1

Informações dos livros: 
Título1: O grande campeão, Autor1: Pinta, Ano1: 2026
Título2: O mar serenou, Autor2: Maria Helena, Ano2: 2024
Título3: A praia, Autor3: Deus, Ano3: 2000


In [9]:
dic = {
    "Nome":"Alice",
    "Idade":20,
    "Curso":"Engenharia de Software"
}

dic["nota"] = 9.5
print(dic)

{'Nome': 'Alice', 'Idade': 20, 'Curso': 'Engenharia de Software', 'nota': 9.5}


In [12]:
produtos= {
    "Fogão":1200.00,
    "Frigideira":500.00,
    "Panela de pressão":1000.00
}

produtos.pop("Fogão")
#comando para remover chave e valor de um dicionário (.pop()).
for chave, valor in produtos.items():
    print(f"Valor do produto {chave}: {valor}")

Valor do produto Frigideira: 500.0
Valor do produto Panela de pressão: 1000.0


In [ ]:
livros = [
  {
    "Título":"Diário de um Banana",
    "Autor":"Pinta",
    "Ano":2014   
  },  

  {
    "Título":"Clareou",
    "Autor":"Pixote",
    "Ano":2025   
  },

  {
    "Título":"O mar",
    "Autor":"Jesus",
    "Ano":1900   
  }             
]

print("Informações dos livros: ")

cont=1

for livro in livros:
  print(f"Título{cont}: {livro["Título"]}, Autor{cont}: {livro["Autor"]}, Ano{cont}: {livro["Ano"]}")
  cont+=1

livros.pop(0)

print("Livros Atualizados!!!")

cont=1
for livro in livros:
  print(f"Título{cont}: {livro["Título"]}, Autor{cont}: {livro["Autor"]}, Ano{cont}: {livro["Ano"]}")
  cont+=1

#E o comando para remover apenas um item de um dicionario dentro dessa lista como por exemplo o título apenas, o comando fica assim: livros[0].pop("Título"). 

Informações dos livros: 
Título1: Diário de um Banana, Autor1: Pinta, Ano1: 2014
Título2: Clareou, Autor2: Pixote, Ano2: 2025
Título3: O mar, Autor3: Jesus, Ano3: 1900
Livros Atualizados!!!
Título1: Clareou, Autor1: Pixote, Ano1: 2025
Título2: O mar, Autor2: Jesus, Ano2: 1900


In [1]:
livros = []

# Definindo quantos livros o usuário quer adicionar
quantidade = int(input("Quantos livros deseja cadastrar? "))

for i in range(quantidade):
    print(f"\nCadastro do livro {i+1}:")
    titulo = input("Título: ")
    autor = input("Autor: ")
    ano = input("Ano: ")
    
    # Criando o dicionário e adicionando à lista
    novo_livro = {
        "Título": titulo,
        "Autor": autor,
        "Ano": ano
    }
    livros.append(novo_livro)

print("\nInformações dos livros: ")

cont=1
for livro in livros:
    print(f"Título{cont}: {livro['Título']}, Autor: {livro['Autor']}, Ano: {livro['Ano']}")
    cont+=1

livros.pop(0)

print("\nLivros Atualizados!!!")

cont=1
for livro in livros:
    print(f"Título{cont}: {livro['Título']}, Autor: {livro['Autor']}, Ano: {livro['Ano']}")
    cont+=1


Cadastro do livro 1:

Cadastro do livro 2:

Informações dos livros: 
Título1: oi, Autor: eu, Ano: 9090
Título2: tchau, Autor: eu, Ano: 0909

Livros Atualizados!!!
Título1: tchau, Autor: eu, Ano: 0909


In [ ]:
import numpy as np

#criar um vetor com o numpy
meu_vetor = np.array([10, 11, 13, 11, 14, 15])
#array é um vetor unidimensional, horizontal ou vertical

#criar matriz 2x3
minha_matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(minha_matrix.shape) #resultado: (2, 3)

#cria tensor == conjunto de matrizes
meu_tensor = np.array([[[1, 2, 3], [4, 5, 6,]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]])
print(meu_tensor.shape) #resultado: (3, 2, 3)

In [6]:
vetor= np.array([1, 2, 3])

vetor= np.append(vetor, [4, 5, 6])
print(vetor)

vetor= np.delete(vetor, 0)
print(vetor)

[1 2 3 4 5 6]
[2 3 4 5 6]


In [ ]:
import numpy as np

a= np.array([9, 6, 12, 16, 20])
b= np.copy(a)
print(a)
print(b)
b[0]=19
print(a)
print(b)
result=np.concatenate((a,b))
print(result)
x, y=np.split(result, 2)
print(x)
print(y)

[ 9  6 12 16 20]
[ 9  6 12 16 20]
[ 9  6 12 16 20]
[19  6 12 16 20]
[ 9  6 12 16 20 19  6 12 16 20]
[ 9  6 12 16 20]
[19  6 12 16 20]


In [11]:
matriz= np.array([(1, 2, 3, 4), (5, 6, 7, 8)])
print(matriz[1, : ])
b= np.copy(matriz)
print(b[0,1:4])

[5 6 7 8]
[2 3 4]


In [ ]:
import numpy as np


a= np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]) #ou usar .arange(x) para preencher a quantidade de números mais rápido
b= a.reshape(3, 4)
print(b)
print (b[1])
print(b[2][3])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[4 5 6 7]
11


In [20]:
a= np.array([1, 2, 3])
b= np.array([4, 5, 6])
c= np.concatenate((a, b))
print(c[1:5])

[2 3 4 5]


In [24]:
a= np.array([10, 20, 30, 40, 50])
b= np.copy(a)
b= np.delete(b, [1, 2])
print(a)
print(b)

[10 20 30 40 50]
[10 40 50]


In [23]:
a= np.array([100, 200, 300, 400, 500, 600])
x, y= np.split(a, 2)
print("Vetores Iniciais:")
print(x)
print(y)

print("Vetores Atualizados: ")
y= np.append(y, 700)
print(x)
print(y)

Vetores Iniciais:
[100 200 300]
[400 500 600]
Vetores Atualizados: 
[100 200 300]
[400 500 600 700]


In [28]:
a= np.array([8, 4, 9, 2])
b= np.array([2, 4, 3, 2.5])
print(a, b)

c= np.add(a, b) #adição dos vetores 
print(c)

c= np.subtract(a, b) #subtração
print(c)

c= np.multiply(a, b) #multiplicação
print(c)

c= np.divide(a, b) #divisão
print(c)

c= np.power(a, b) #potência
print(c)

c= np.sqrt(a) #raiz quadrada
print(c)

[8 4 9 2] [2.  4.  3.  2.5]
[10.   8.  12.   4.5]
[ 6.   0.   6.  -0.5]
[16. 16. 27.  5.]
[4.  1.  3.  0.8]
[ 64.         256.         729.           5.65685425]
[2.82842712 2.         3.         1.41421356]


In [5]:
import numpy as np

a= np.array([[1], [2], [3]])
b= np.array([10, 20, 30])
c= a+b
print(a)
print(b)
print(c)

[[1]
 [2]
 [3]]
[10 20 30]
[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [9]:
a= np.array([10, 20, 30 , 40, 50])
b= np.array([1, 2, 3, 4, 5])
print(a)
print(b)

c= np.add(a, b)
print(c)
c= np.subtract( a, b)
print(c)
c= np.multiply(a, b)
print(c)
c= np.divide(a, b)
print(c)

[10 20 30 40 50]
[1 2 3 4 5]
[11 22 33 44 55]
[ 9 18 27 36 45]
[ 10  40  90 160 250]
[10. 10. 10. 10. 10.]


In [12]:
a= np.array([12, 15, 20, 25, 30, 35, 40])
print(a)

c= np.sum(a)
print(c)
c= np.mean(a)
print(c)
c= np.median(a)
print(c)
c= np.max(a)
print(c)
c= np.min(a)
print(c)

[12 15 20 25 30 35 40]
177
25.285714285714285
25.0
40
12


In [5]:
import numpy as np

a= np.array([[1, 2, 3], [4, 5, 6]])
b= np.array([10, 20, 30])

c= a+b
print(c)

d= np.multiply(c, 2)
print(d) 

[[11 22 33]
 [14 25 36]]
[[22 44 66]
 [28 50 72]]


In [6]:
a= np.array([[10], [20], [30]])
b= np.array([1, 2, 3])

c= np.multiply(a, b)

print(a)
print(b)
print(c)

[[10]
 [20]
 [30]]
[1 2 3]
[[10 20 30]
 [20 40 60]
 [30 60 90]]
